---
abstract: 'Blocks bad MTA behavior using IPTables and Redis.'
author:
  - 'Tamer Rizk <foss@inficron.com>'
build_requires:
  Email::Simple: '2.0'
  Test::More: '0.88'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mail-SpamAssassin-Contrib-Plugin-IPFilter
no_index:
  directory:
    - inc
requires:
  MIME::Base64: '3.0'
  MIME::Lite: '3.0'
  Mail::SpamAssassin: '3.0'
  Math::Round: '0'
  Redis: '1.5'
  perl: '5.010'
version: '0.93'
